### PR TITLE
Array Operations in C

### LINKED ISSUE #261: Operations on Array in C
Operations on Array includes Traversing, Insertion, Searching, Deletion and Sorting.

**Language**

-   [ ] Python
-   [ ] Java
-   [x] C
-   [ ] C++

### PR DESCRIPTION
**Pull request by Gaurisha21**
Fixes: #261

### CODE REVIEW

**Comment by kaustubhgupta** [comment]
https://github.com/kaustubhgupta/Hacktoberfest2020_/issues/261#issuecomment-705490732
It means that the bot is suggesting some changes to the code. If you click on details, you will see the changes. Please change as suggested by it

**Comment by kaustubhgupta** [comment]
@Gaurisha21 Also bring back the PR template and fill it. You have removed it!

**Comment by kaustubhgupta** [comment]
Also, update the readme of the C folder with your entry

**Comment by Gaurisha21** [comment]
@kaustubhgupta I have identified the changes to be done, and I am working on it. 
I wanted to know if this is the only forum to discuss or to ask doubts?

**Comment by kaustubhgupta** [comment]
@Gaurisha21 Yes PR comments or Issue comments

**Comment by kaustubhgupta** [comment]
@Gaurisha21 Make changes suggested by code factor plus update the readme of the C folder with your entry

**Comment by Gaurisha21** [comment]
Okay, I'll do it asap.

**Comment by kaustubhgupta** [comment]
Due to inactivity, this PR has been closed

**Pull request closed without merging**
