### PR TITLE
Copy content of one directory in other.

### LINKED ISSUE #78: Directory Handler
**Issue available in C, C++ and Python implementation**

# Directory Handler

- Implement a system that takes two file paths and copies all the files and directories and their content from the first path and duplicates them in the second path.
- use file handling

## Bug Reports
Please replace this line with a brief summary of your issue AND if reporting a build issue include the link.

- [ ] Didn't run?
- [ ] Permission Issues?
- [ ] Broken Links
- [ ] Other Issues? (Add Here)

## Any links, resources, or references to solve the issue?
- [ ] Yes

If yes, please the resources in the following format:
- Resource 1
- Resource 2

- [ ] No

### PR DESCRIPTION
**Pull request by CuriousMonkey7**
# Java program to copy content of one directory to other.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
This program take source and destination path as input and copy the content of source file/directory to given file/directory.
if destination file or directory doesn't exist it creates one. But if source file doesn't exist or source path is wrong it terminate with relevant message.

Fixes #78

## 

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generates no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by YashSaxena9 — CHANGES_REQUESTED** [review]
The code works but has bugs, needs improvement.

**Comment by YashSaxena9** [comment]
Changes and debugging required.

- Please complete the documentation/ comments for the functioning of the code.
- Bug: if the destination path is inside the source path, recursive copying occurs.

Visual display of the Bug

**Comment by CuriousMonkey7** [comment]
Okay got it, working on it.

**Comment by YashSaxena9** [comment]
Unnecessary **.DS_store** file detected, remove it, also don't add .gitignore file on your own, only collaborators are allowed to change/upload these files.

**Comment by CuriousMonkey7** [comment]
Deleted .DS_Store and .gitignore file. I will keep this in mind from next time.

**Review by YashSaxena9 — APPROVED** [review]
Code reviewed, looks good for merge

**Comment by YashSaxena9** [comment]
It seems like you accidentally added the file outside the java folder, please put your code in the appropriate language folder. Then it should be good to merge. :)

**Comment by kaustubhgupta** [comment]
@100RABHpy 
Final check:
Update the readme of java directory

**Comment by kaustubhgupta** [comment]
@100RABHpy Thanks for contributing !

**Comment by CuriousMonkey7** [comment]
Pleasure is all mine :)

**Pull request merged**
