### PR TITLE
Palindrome Substrings

### PR DESCRIPTION
**Pull request by keerti2001**
# Palindromic Substrings

I have added a C++ program for finding all possible continuous subsequences of an array and print the ones which are a palindrome.

Fixes # 85

Also added comments and relevant documentation

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generates no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by kaustubhgupta** [comment]
@keerti2001 please edit the PR template to fill the title, short description, and issue number

**Comment by keerti2001** [comment]
Yes sir

**Comment by YashSaxena9** [comment]
Merge Approved!

**Review by YashSaxena9 — COMMENTED** [review]
code reviewed

**Pull request merged**
