### PR TITLE
Palindrome Substrings

### LINKED ISSUE #73: Palindromic Substrings
**This issue is open for C Implementation**
Palindromic substrings

Make a program to find all possible continuous subsequences of an array and print the ones which are a palindrome.

## Bug Reports
Please replace this line with a brief summary of your issue AND if reporting a build issue include the link.

- [ ] Didn't run?
- [ ] Permission Issues?
- [ ] Broken Links
- [ ] Other Issues? (Add Here)

## Any links, resources or references to solve the issue?
- [ ] Yes

If yes, please the resources in the following format:
- Resource 1
- Resource 2

- [ ] No

### PR DESCRIPTION
**Pull request by deVedant**
# Palindrome Substrings

Program in python to find all palindrome substrings in a user string input.
Fixes #73  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by kaustubhgupta** [comment]
Absolutely Nonsense, you are making PR from another user contribution to your forked repo! Spammed PR. Reported to Hacktoberfest team

**Comment by deVedant** [comment]
> Absolutely Nonsense, you are making PR from another user contribution to your forked repo! Spammed PR. Reported to Hacktoberfest team

Hey brother it was my another GitHub account. I actually forked in that account , so I created a PR from that account and then committed changes and hence there were two commits. Check it's MarkVed17(Vedant) and deVedant(Vedant). Both are my accounts. Sorry for the incovenience.

**Comment by YashSaxena9** [comment]
Multiple user accounts are considered spam accounts, use only one account, it is a clear violation of the contribution guide.
PR from spam accounts will be considered plagiarised.

**Comment by deVedant** [comment]
Dude you don't even make sense.
Professionals use SSH keys for they have multiple accounts. I was trying that since yesterday but the issue doesn't seem to solve. 
Here’s the ss :



I was even trying this for other repo but idk what is this issue. I couldn't use Git using VSCode thanks to this issue. 


I thought my alibi was apt but unfortunately you're not getting my point.

**Comment by kaustubhgupta** [comment]
If you still wish to contribute, have a look at issues and repo folders to see if your problem has been solved or not. If yes then we can't do anything else make an issue and this time work only with one account

**Pull request closed without merging**
