### PR TITLE
Added Counting Sort in Python

### LINKED ISSUE #549: Counting Sort for Python
# Description
Counting Sort

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Python: @rupesh-kumar-lpu

### PR DESCRIPTION
**Pull request by rupeshkumar22**
# Description

Documented Example in file 

Fixes #549

## Type of change

**Please delete options that are not relevant**

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

# Checklist:

-   [x] I have read the contribution guidelines before making this PR.
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented in my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation (Language folder or any other readme instructed to)
-   [x] My changes generates no new warnings
-   [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
Make the changes suggested by codefactor bot

**Comment by rupeshkumar22** [comment]
Okay

**Comment by rupeshkumar22** [comment]
Please review the change @kaustubhgupta

**Review by rupeshkumar22 — COMMENTED** [review]
Updated

**Pull request merged**
