### PR TITLE
Added Calculator program and menu screenshot

### LINKED ISSUE #125: I want to add a calculator with more than just basic functions using C language
Please include a small description or summary of the issue here.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Languages**
- [ ] Python
- [ ] Java
- [x] C
- [ ] C++

I will be adding a calculator with sqrt, log, power func along with basic operations using C language
[c calculator for github.txt](https://github.com/kaustubhgupta/Hacktoberfest2020_/files/5319449/c.calculator.for.github.txt)

### PR DESCRIPTION
**Pull request by b-samarth**
# Java Calculator

Command Line Calculator written in java with more functionality such as calculation of nth root, roots of quadratic equation and much more
Fixes #125 

## Type of change

Please delete options that are not relevant.

-   [x] New feature (non-breaking change which adds functionality)

# Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] My changes generates no new warnings
-   [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by b-samarth** [comment]
Can anyone explain what is the all checks have failed warning?
What does it imply?

**Comment by kaustubhgupta** [comment]
@b-samarth update the JAVA readme file

**Comment by YashSaxena9** [comment]
The code looks fine, add your file to the java README's content table

**Review by YashSaxena9 — APPROVED** [review]
Code reviewed

**Comment by YashSaxena9** [comment]
> Can anyone explain what is the all checks have failed warning?
> What does it imply?

You have added a png file, which is not readable by our automated code validator.

**Comment by kaustubhgupta** [comment]
@b-samarth update the readme of java directory, everything looks fine

**Comment by b-samarth** [comment]
> > Can anyone explain what is the all checks have failed warning?
> > What does it imply?
> 
> You have added a png file, which is not readable by our automated code validator.

So shall I change it to a jpg file or leave it to the same?

**Comment by kaustubhgupta** [comment]
> > > Can anyone explain what is the all checks have failed warning?
> > > What does it imply?
> > 
> > 
> > You have added a png file, which is not readable by our automated code validator.
> 
> So shall I change it to a jpg file or leave it to the same?

No issues for png, bot is broken, will fix it soon!

**Comment by b-samarth** [comment]
> @b-samarth update the readme of java directory, everything looks fine

Can you guide me on how to update the java README from my own branch as it is showing a conflict as I made the push.

**Comment by kaustubhgupta** [comment]
@b-samarth I have resolved the conflict, the problem was that someone else updated the readme before your's code. To resolve this I simply committed the change into your forked repo. I hope you had a great time learning something new this hacktoberfest!

**Comment by b-samarth** [comment]
> committed the change into your forked repo. I hope you had a great time learning somet

Yeah I appreciate your help. I really enjoyed.

**Pull request merged**
