### PR TITLE
Binary Search Tree implementation in C

### LINKED ISSUE #77: Binary Search Tree implementation
# Binary Search Tree

Implement a Binary Search Tree with all basic methods like traversals, update, deletion, addition, and finding of data.

# Assignees:

- C: @Harshalszz
- C++: @keerti2001
- Python:
- Java

### PR DESCRIPTION
**Pull request by Harshalszz**
# Title < BST in C>

Fixes #77

## Type of change
Added BinarySearchTree.c file

# Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generates no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by YashSaxena9 — CHANGES_REQUESTED** [review]
PR acceptable for merge but please add the following functions first :
- Pre-order traversal
- Post-order traversal

**Comment by Harshalszz** [comment]
ok sir I will add them.

**Comment by Harshalszz** [comment]
Done sir. I have added preorder and postorder traversal.

**Review by YashSaxena9 — APPROVED** [review]
Code reviewed, accepted for merge :D

**Pull request merged**
