### PR TITLE
Factorial using stack

### PR DESCRIPTION
**Pull request by 13snehitha**
# 343-print factorial of a number using stack, full code in java

Please include a summary of the changes you have made in regard with this issue. 

Fixes #(issue number)

## Type of change

**Please delete options that are not relevant**

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

# Checklist:

-   [ ] I have read the contribution guidelines before making this PR.
-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented in my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation (Language folder or any other readme instructed to)
-   [ ] My changes generates no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by 13snehitha** [comment]
@kaustubhgupta 
All the errors are handled and the code can now be merged

**Comment by kaustubhgupta** [comment]
PR template ??

**Comment by 13snehitha** [comment]
@kaustubhgupta 
The error is resolved. It can be merged now

**Comment by YashSaxena9** [comment]
You are essentially just using 1 integer space in the name of stack.

**Pull request closed without merging**
