### PR TITLE
Kadane

### LINKED ISSUE #287: Kadane's Algorithm
Write an efficient program to find the sum of contiguous subarray within a one-dimensional array of numbers which has the largest sum.

**Is your feature request related to a problem? Please describe.**
It is not a problem. It is an efficient algorithm to find largest subarray in sum in O(n) complexity

**Describe the solution you'd like**
Simple idea of the Kadane’s algorithm is to look for all positive contiguous segments of the array.

**Additional context**

**Languages**

-   [x] Python : @13snehitha
-   [x] Java : @DefCon-018
-   [x] C: @rgarg-2711
-   [x] C++: @Blackwidow2981

### PR DESCRIPTION
**Pull request by Blackwidow2981**
Kadane's Algorithm Implementation in C++.
I have added the required Documentation and the code for Kadane's algorithm .

Fixes #287

New Code
# Checklist:

-   [X] I have read the contribution guidelines before making this PR.
-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my own code
-   [X] I have commented in my code, particularly in hard-to-understand areas
-   [X] I have made corresponding changes to the documentation (Language folder or any other readme instructed to)
-   [X] My changes generates no new warnings
-   [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Blackwidow2981** [comment]
Hi @kaustubhgupta . I think the bug from the last pull request has been rectified. Kindly review it . Sorry about the trouble.

**Review by kaustubhgupta — APPROVED** [review]

**Comment by kaustubhgupta** [comment]
Perfect! @Blackwidow2981 I hope you had a great time contributing here and reached your goals in hacktoberfest! Happy open-source journey!

Also, I am glad to share that this PR was 100th hacktoberfest-accepted PR! May I ask if it's okay if I use your identity to celebrate this on social media?

**Comment by Blackwidow2981** [comment]
Hey , Yes for sure !that would be great . Wohoo 100th PR that is amazing !Do let me know where you are putting it up . I would love to share it too !

**Comment by kaustubhgupta** [comment]
@Blackwidow2981 Here is the LinkedIn post I made today:
https://www.linkedin.com/posts/kaustubh-gupta-612767ab_hacktoberfest-pr-maintainer-activity-6723481377909596160-f39h

Also, I have updated the repo readme with this milestone

**Comment by Blackwidow2981** [comment]
Yep Got it! I'll share it too! Thank You for the Opportunity!

**Comment by Blackwidow2981** [comment]
Hi @kaustubhgupta .My hacktoberfest account still shows that this PR Is under review .I have absolutely no idea why.Can you tell me why what to do about it?

**Comment by kaustubhgupta** [comment]
Hi @Blackwidow2981, Actually Hacktoberfest matures the PR after 14 days. So as this PR was merged 12 days ago, after 2 days it will show ticked and accepted. Let me know if you have other quires 😄

**Pull request merged**
