### PR TITLE
Grading prog. of an University

### PR DESCRIPTION
**Pull request by rahul-7077**
The first line contains a single integer, n, the number of students.
Each line i of the n  subsequent lines contains a single integer, grades[i].

### CODE REVIEW

**Comment by kaustubhgupta** [comment]
@rahul-7077 Please create an issue of this, get it assigned, and then fill the PR template which you have completely deleted.

**Comment by kaustubhgupta** [comment]
Also, make the changes suggested by codefactor

**Comment by rahul-7077** [comment]
I don't know how to do this... I'm using GitHub for the first time.

Sent from Yahoo Mail on Android 
 
  On Wed, Oct 7, 2020 at 10:29 PM, Kaustubh<notifications@github.com> wrote:   


Also, make the changes suggested by codefactor

**Comment by kaustubhgupta** [comment]
@rahul-7077 That's why this hactoberfest was started. Read the contribution guidelines to get all the info. Also, as these changes were made from the master branch I can't merge this PR  so this will be closed

**Comment by rahul-7077** [comment]
It's your wish... 

Sent from Yahoo Mail on Android 
 
  On Wed, Oct 7, 2020 at 10:35 PM, Kaustubh<notifications@github.com> wrote:   


@rahul-7077 That's why this hactoberfest was started. Read the contribution guidelines to get all the info. Also, as these changes were made from the master branch I can't merge this PR so this will be closed

**Pull request closed without merging**
