### PR TITLE
Merge Sort Algorithm implemeted in Java

### PR DESCRIPTION
**Pull request by meghamalviya5**
# Description

The program implements MergeSort algorithm in java programming language using the Divide ad Conquer Strategy.
The Time Complexity of the program in the worst case is O(nlogn) where 'n' is the number of elements in the given array. Whereas its worst case Space Complexity is O(h) where 'h' is the maximum number of elements present at any point in stack section of memory during execution of the program.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generates no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by YashSaxena9 — APPROVED** [review]
Lousy implementation of Merge Sort.
Can be optimized.

**Comment by meghamalviya5** [comment]
Thanks for reviewing. Will try to optimize

**Comment by meghamalviya5** [comment]
> Lousy implementation of Merge Sort.
> Can be optimized.

Could you point out what can be optimised?

**Comment by YashSaxena9** [comment]
> Could you point out what can be optimized?

- The variable naming conventions can be improved for more readability. Read this for more understanding [Click Me!](https://medium.com/@rhamedy/a-short-summary-of-java-coding-best-practices-31283d0167d3)

- Merge function have 3 loops that increase code redundancy, can be packed in 1 loop.

- MergeSort function has manually handled arrays, code can be optimized into fewer lines of code. Return type array can also be used to use and take benefit of previously allocated memory.

- Use of DocType multiline comments is encouraged instead of single line scattered comments.

**Comment by meghamalviya5** [comment]
> 
> 
> > Could you point out what can be optimized?
> 
>     * The variable naming conventions can be improved for more readability. Read this for more understanding [Click Me!](https://medium.com/@rhamedy/a-short-summary-of-java-coding-best-practices-31283d0167d3)
> 
>     * Merge function have 3 loops that increase code redundancy, can be packed in 1 loop.
> 
>     * MergeSort function has manually handled arrays, code can be optimized into fewer lines of code. Return type array can also be used to use and take benefit of previously allocated memory.
> 
>     * Use of DocType multiline comments is encouraged instead of single line scattered comments.

okay thanks. But if I try reducing the space complexity (as mentioned in 3rd point) it would result in increase in time complexity of the program.

**Comment by YashSaxena9** [comment]
> > > Could you point out what can be optimized?
> > 
> > 
> > ```
> > * The variable naming conventions can be improved for more readability. Read this for more understanding [Click Me!](https://medium.com/@rhamedy/a-short-summary-of-java-coding-best-practices-31283d0167d3)
> > 
> > * Merge function have 3 loops that increase code redundancy, can be packed in 1 loop.
> > 
> > * MergeSort function has manually handled arrays, code can be optimized into fewer lines of code. Return type array can also be used to use and take benefit of previously allocated memory.
> > 
> > * Use of DocType multiline comments is encouraged instead of single line scattered comments.
> > ```
> 
> okay thanks. But if I try reducing the space complexity (as mentioned in 3rd point) it would result in increase in time complexity of the program.

No, it won't, you just need to write it efficiently enough, also as you are working with array references so you can also try returning the array instead of copying it over and over.

**Pull request merged**
