### PR TITLE
Create DynamicQueue.c

### PR DESCRIPTION
**Pull request by KingBasak**
This code follows the FIFO system of the queue and also the space for the elements is given dynamically to reduce any space complexity.

A queue code with dynamic memory allocation.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change. < Edit this part>

Fixes # (issue)

## Type of change
-   [x] New feature (non-breaking change which adds functionality)
# Checklist:
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generates no new warnings
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by kaustubhgupta** [comment]
- This PR is not associated with any issue therefore closing it
- Neither you asked any issue to be assigned to you

**Comment by KingBasak** [comment]
I added a new c code in files which runs fine so, how is it invalid?

**Comment by kaustubhgupta** [comment]
> I added a new c code in files which runs fine so, how is it invalid?

- Changes made through the master branch
- No issue assigned to you with respect to this PR neither an issue exist for this 
- To still contribute, follow guidelines

**Comment by KingBasak** [comment]
That ok, and thank you for telling me, at least you could have said that you are not accepting any new(C-code) contribution and you are only working to solve only the issues specified in the project, Before putting an unnecessary INVALID label on my contribution.
I would have closed my pull request and follow the issues only.
This behavior is totally unexpected. Anyways good luck with your project.😃

**Comment by kaustubhgupta** [comment]
> at least you could have said that you are not accepting any new(C-code) contribution and you are only working to solve only the issues specified in the project, Before putting an unnecessary INVALID label on my contribution.

It is better to have a look at these guidelines before making any comment https://github.com/kaustubhgupta/Hacktoberfest2020_/blob/master/CONTRIBUTING.md

This is also in a pinned issue. Also, on the top of the README of this project, it is mentioned to read this issue.

**Comment by kaustubhgupta** [comment]
@KingBasak 
Okay that was rude from my part, apologies
Can you make another PR so that I can merge your code?

**Pull request closed without merging**
