### PR TITLE
Add Priyal Gupta to Contributors list

### PR DESCRIPTION
**Pull request by priyalgupta09**
# Description

Please include a summary of the changes you have made in regard with this issue. 

Fixes #(issue number)

## Type of change

**Please delete options that are not relevant**

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

# Checklist:

-   [ ] I have read the contribution guidelines before making this PR.
-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented in my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation (Language folder or any other readme instructed to)
-   [ ] My changes generates no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by kaustubhgupta** [comment]
Template not filled,
Bucket sort not uploaded,
edit name of the PR

**Comment by priyalgupta09** [comment]
@kaustubhgupta  but bucket sort is another name of radix sort.
they have same algorithm.

**Comment by kaustubhgupta** [comment]
https://stackoverflow.com/questions/4461737/what-is-the-difference-between-bucket-sort-and-radix-sort#:~:text=Bucket%20sort%20and%20radix%20sort%20are%20close%20cousins%3B%20bucket%20sort,particular%20how%20do%20they%20differ%3F

you need to have a look at this

**Comment by YashSaxena9** [comment]
> @kaustubhgupta but bucket sort is another name of radix sort.
> they have same algorithm.

No, both of them are different

**Comment by kaustubhgupta** [comment]
PR closed due to inactivity

**Pull request closed without merging**
