### PR TITLE
add files via upload

### PR DESCRIPTION
**Pull request by adilsp5075**
# Title/Heading < Edit this part>

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change. < Edit this part>

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generates no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by kaustubhgupta** [comment]
Please try to understand you are making wrong PRs! Have a look at contribution guidelines. Also, Calculator in C is already assigned to someone else

**Comment by adilsp5075** [comment]
I am following your instructions but I can't send a pull request from the
contribution branch when I try to send a request as per the instructions
provided it shows there is nothing to compare so I upload the file to the
main branch and send the pull request
It's my first attempt in hacktober fest
I don't know what I really do

**Comment by kaustubhgupta** [comment]
@adilsp5075 as you mentioned that you are new to Github and it's absolutely fine to make mistakes. Here are the next steps for your next PR:
- Delete the forked repo from your account.
- Fork it again.
- Create a separate branch.
- Look at the current issues and see which issue you can contribute in. Make sure that the issue has not been already done by someone else in that language. After you are sure that a particular issue is not solved by anyone else, comment on the issue that you want to work on that particular issue.
- After that, you will be assigned that issue by any of the mentors. 
- Then make the PR and **make sure to fill the template properly, you haven't filled the template both of the time**. Also, place the files in appropriate folders and update the readme of the same

**Comment by adilsp5075** [comment]
Thanks for the new information
I will check it out

**Pull request closed without merging**
