### PR TITLE
Getting Started with Spring Boot : Hello World Grettings Application

### PR DESCRIPTION
**Pull request by pmanaktala**
A sample application using Spring Boot for anyone who is willing to learn. It is the most basic Hello World application. 
A highly in demand language which can be used to create Microservices!

Attaching the files as request

image

### CODE REVIEW

**Comment by kaustubhgupta** [comment]
I really didn't understand the whole codebase. Can you elaborate on what this is all about and why there are 17 files related to this?

**Comment by pmanaktala** [comment]
Basically it is a application which lets you create API's using spring boot. Spring Boot makes it easy to create stand-alone, production-grade Spring based Applications that you can "just run". This application is a starter app that anyone can take a reference when they are trying to learn spring boot. Here you follow a MVC architecture where there are model, views and controllers each designed for different purposes. 
<br>
In nutshell
Controller is something that interacts with the user/other spring boot application. It exposes a REST endpoint for you. Service/ServiceImpl is where business logic goes. DTO/Entity is your POJO classes which is used only and only to transfer data between layer. They do not have any business logic what so ever. 

Please refer to the readme file for links and other info.

**Comment by pmanaktala** [comment]
Here this code creates a REST GET endpoint which will return a greeting to user. (This can be changed for actual business logic later as per specific use) 

GET /greet/{username}

You need POSTMAN to invoke this. But since it was a GET request i used chrome. Other REST Requests will require POSTMAN

**Comment by YashSaxena9** [comment]
Unnecessary dependencies included.

**Comment by pmanaktala** [comment]
@YashSaxena9 may i know which dependencies are extra here? As far as i can see there are literally two dependencies. One is for testcase and one is for spring web.

**Pull request closed without merging**
