### PR TITLE
Added Counting Sort algorithm in C++

### LINKED ISSUE #522: Counting sort algo
# Description
Hello! I want to contribute to this repo by adding a counting sort algorithm in C++.

# Additional context
-- Not required --

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Java: @namitamutha 
-   [x] C++: @dishantvyas15

### PR DESCRIPTION
**Pull request by dishantvyas15**
# Description

Adding a code implementing the counting sort algorithm in C++.
Reference: 
Fixes: #522

## Type of change

-   [x] New feature (non-breaking change which adds functionality)

# Checklist:

-   [x] I have read the contribution guidelines before making this PR.
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented in my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation (Language folder or any other readme instructed to)
-   [x] My changes generates no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by kaustubhgupta — COMMENTED** [review]
The comments are highly unformatted. The correct way is having two spaces after the code line, then '//' and after one space you can quote the comments.
```c++
cout << "hello";  # This is a valid comment 
```

**Comment by dishantvyas15** [comment]
@kaustubhgupta I've made the necessary changes.
Review requested.

**Comment by dishantvyas15** [comment]
@kaustubhgupta 
Thank you for consideration..!

**Comment by kaustubhgupta** [comment]
@dishantvyas15 You're welcome. I am glad to share this that you are the 100th contributor to this repository! Congrats and all the best for future endeavors!

**Comment by dishantvyas15** [comment]
Wow, that's great 🥳🥳
@kaustubhgupta Good luck to you as well, for future triumphs!

**Pull request merged**
