### PR TITLE
Quick sort in C

### LINKED ISSUE #283: Quick sort
Like Merge Sort, QuickSort is a Divide and Conquer algorithm. It picks an element as pivot and partitions the given array around the picked pivot

**Is your feature request related to a problem? Please describe.**
It is a sorting algorithm with time complexity O(nlogn)

**Describe the solution you'd like**
I want to sort an array

**Additional context**

**Languages**

-   [x] Python: @rosse 
-   [x] Java: @chAlekhya
-   [x] C: @neha07kumari 
-   [x] C++ : @DefCon-018

### PR DESCRIPTION
**Pull request by neha07kumari**
# Description

Please include a summary of the changes you have made in regard with this issue. 

Fixes #283 

# Checklist:

-   [x] I have read the contribution guidelines before making this PR.
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented in my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation (Language folder or any other readme instructed to)
-   [x] My changes generates no new warnings
-   [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by neha07kumari** [comment]
Please check it . @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@neha07kumari How I will check when you haven't filled the PR template. Neither you gave a good title of the PR nor filled the issue number. How do I know which issue you are referring to? Please edit it carefully

**Comment by neha07kumari** [comment]
@kaustubhgupta  I have added my issue number

**Comment by kaustubhgupta** [comment]
I cannot see the forked repo and branch from where you have pushed this code therefore this PR stands canceled

**Pull request closed without merging**
