### PR TITLE
create folder linked list

### LINKED ISSUE #142: I want to add more Linked List algorithims in C
I want to add more Linked List algorithms in C

**Is your feature request related to a problem? Please describe.**
These are basic Linked List algos

**Describe the solution you'd like**
I'll be adding the solutions

**Additional context**
From my GitHub [thisisrick25](https://github.com/thisisrick25/data-structures-and-algorithim)

**Languages**

-   [ ] Python
-   [ ] Java
-   [x] C
-   [ ] C++

### PR DESCRIPTION
**Pull request by thisisrick25**
# Linked List

Contains basic linked list algorithms

Fixes #142 

## Type of change

Please delete options that are not relevant.

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)

# Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generates no new warnings
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes
-   [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by YashSaxena9** [comment]
Please collapse multiple file content to one, you can segregate functions separately with a docType comment to explain functionality. You need to minimize code redundancy as we already have most of these features implemented.

**Review by YashSaxena9 — CHANGES_REQUESTED** [review]
Collapse content in a single file to minimize code redundancy and duplicity.

**Comment by kaustubhgupta** [comment]
@YashSaxena9 don't you think it's all copied? I mean single PR for 5 different functions? Also, readme has not been updated. Should we proceed with this?

**Comment by YashSaxena9** [comment]
> @YashSaxena9 don't you think it's all copied? I mean single PR for 5 different functions? Also, readme has not been updated. Should we proceed with this?

Yes, probably these are plagiarized code, I have my suspicions. Will take action in case code is not improve sooner!

**Comment by thisisrick25** [comment]
I'm new to GitHub also I've made changes in a new commit and yes I've written all the 5 functions for single PR. I don't really understand what you mean by 'copied'.

**Comment by YashSaxena9** [comment]
PR is being rejected for plagiarism suspicion.
- You deleted all the functions and left only 3 functions, which doesn't add up if you actually wrote your code yourself. You should've been able to resolve multiple files into a single one.
- Code format and coding style completely changed.
- Content of deleted files still missing.
- Violation of contribution guide.
- The functions you want to add already exists.

**Pull request closed without merging**
