### PR TITLE
Kadane's algorithm

### LINKED ISSUE #287: Kadane's Algorithm
Write an efficient program to find the sum of contiguous subarray within a one-dimensional array of numbers which has the largest sum.

**Is your feature request related to a problem? Please describe.**
It is not a problem. It is an efficient algorithm to find largest subarray in sum in O(n) complexity

**Describe the solution you'd like**
Simple idea of the Kadane’s algorithm is to look for all positive contiguous segments of the array.

**Additional context**

**Languages**

-   [x] Python : @13snehitha
-   [x] Java : @DefCon-018
-   [x] C: @rgarg-2711
-   [x] C++: @Blackwidow2981

### PR DESCRIPTION
**Pull request by Blackwidow2981**
Kadane's Algorithm Implementation in C++.
I have added the required Documentation and the code for Kadane's algorithm .

Fixes #287 

New Code

# Checklist:

-   [X] I have read the contribution guidelines before making this PR.
-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my own code
-   [X] I have commented in my code, particularly in hard-to-understand areas
-   [X] I have made corresponding changes to the documentation (Language folder or any other readme instructed to)
-   [X] My changes generates no new warnings
-   [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by kaustubhgupta** [comment]
Pushed extra python files, have a check of that

**Comment by Blackwidow2981** [comment]
Oops,I will have that looked into.

**Comment by Blackwidow2981** [comment]
Made the required changes  @kaustubhgupta .Please review it .

**Comment by kaustubhgupta** [comment]
There seems to be a big error from your side. If I merge this PR, the master Python readme file will be deleted. I would suggest making a new PR.

**Pull request closed without merging**
