### PR TITLE
Fast io

### LINKED ISSUE #91: Fast IO for Java
# Fast IO for Java

Implement classes for fast input and output in java using only raw input reader, streams, and writers.

:warning: **Use of Scanner class prohibited**

Requires
- [x] proper documentation
- [x] Easy to understand logic
- [x] Good space and time complexity
- [x] Less code redundancy
- [x] No plagiarism

### PR DESCRIPTION
**Pull request by ghost**
# Create Fast IO Reader and Writer

This implements Fast IO for Java.
This creates Reader and Writer which can be used to easily write to files and read from files.

Fixes: #91 

## Type of change

-   [x] New feature (non-breaking change which adds functionality)

# Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generates no new warnings
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes
-   [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ghost** [comment]
How can I make these tests locally?

**Comment by YashSaxena9** [comment]
@ransbachm have you hosted this code somewhere else on the internet? It seems pretty similar to the ones available online, even the variable names match. Please clarify so that we can come to a decision.

**Comment by ghost** [comment]
I of course did some research but this is self written. I think I did not look a old code of mine. I always use these variable names (using the capital letters as variable name). This is just learnt from online guides. I also use a style that matches their style but I did not copy this. Would you be able to provide me with links to these guides?

**Comment by YashSaxena9** [comment]
> I of course did some research but this is self written. I think I did not look a old code of mine. I always use these variable names (using the capital letters as variable name). This is just learnt from online guides. I also use a style that matches their style but I did not copy this. Would you be able to provide me with links to these guides?

Your code logic, comments and variable names surely follow the best practices recommended but your code seemed similar to some codes hosted on some public repositories.

**Review by YashSaxena9 — CHANGES_REQUESTED** [review]
On some second thoughts, your PR is acceptable for merge but make the following changes.
Please remove the test output file and edit the language folder's readme. :)

**Comment by ghost** [comment]
Changes done.
@YashSaxena9

**Review by kaustubhgupta — APPROVED** [review]

**Pull request merged**
