### PR TITLE
Add discord messager bot

### LINKED ISSUE #483: Discord bot to send messages in any server/channel
# Description
Create a bot to send messages every single x seconds in any server and channel in discord you want
you have to pass email and password, the server name, channel name, is_nsfw flag, time between messages and the array of messages.

# Additional context
Add any other context, links references or screenshots about the feature request here.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Python: @pedrosv20

### PR DESCRIPTION
**Pull request by pedrosv20**
# Description

This bot send messages in random order to any channel you want.

Fixes #483 

## Type of change

**Please delete options that are not relevant**
-   [x] New feature (non-breaking change which adds functionality)

# Checklist:
-   [x] I have read the contribution guidelines before making this PR.
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented in my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation (Language folder or any other readme instructed to)
-   [x] My changes generates no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
Can you add a GIF or Image showing the working of the script?

**Comment by kaustubhgupta** [comment]
Also, delete the chrome driver as it changes every month

**Comment by pedrosv20** [comment]
@kaustubhgupta I added an accelerated gif to show the bot working, it logs in, enters your channel and is sending the randomly input messages with the time delay inserted

**Comment by kaustubhgupta** [comment]
@pedrosv20 I can't see any commit related to GIF. Are you sure you added the file?

**Comment by pedrosv20** [comment]
Sorry i uploaded it but forgot to push

**Review by kaustubhgupta — APPROVED** [review]

**Comment by kaustubhgupta** [comment]
@pedrosv20 perfect now! Thanks for contributing

**Pull request merged**
